# Generated by Django 4.0.2 on 2022-02-27 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vscode', '0003_alter_port_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Port',
            new_name='Docker',
        ),
    ]
