# Generated by Django 4.0.2 on 2022-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vscode', '0004_rename_port_docker'),
    ]

    operations = [
        migrations.AddField(
            model_name='docker',
            name='container',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
